site_name: KSQL
site_url: https://ksql.readthedocs.io
site_description: KSQL docs test site
site_author: Confluent

repo_url: https://github.com/JimGalasyn/JimGalasyn.github.io
edit_uri: ""

theme:
    name: mkdocs
    highlightjs: true
    hljs_languages:
        - yaml
        - django

nav:
    - Home: index.md
    - Concepts:
        - KSQL Architecture: concepts/ksql-architecture.md
        - KSQL and Kafka Streams: concepts/ksql-and-kafka-streams.md
        - Time and Windows in KSQL: concepts/time-and-windows-in-ksql-queries.md
    - Developer Guide:
        - Aggregate Streaming Data With KSQL: developer-guide/aggregate-streaming-data.md
        - KSQL REST API Reference: developer-guide/api.md
        - Create a KSQL Stream: developer-guide/create-a-stream.md
        - Create a KSQL Table: developer-guide/create-a-table.md
        - Implement a User-defined Function (UDF and UDAF): developer-guide/implement-a-udf.md
        - Join Event Streams with KSQL: developer-guide/join-streams-and-tables.md
        - KSQL-Connect Integration: developer-guide/ksql-connect.md
        - KSQL Testing Tool: developer-guide/ksql-testing-tool.md
        - KSQL Processing Log: developer-guide/processing-log.md
        - Query With Arrays and Maps: developer-guide/query-with-arrays-and-maps.md
        - Query With Structured Data: developer-guide/query-with-structured-data.md
        - KSQL Serialization: developer-guide/serialization.md
        - KSQL Syntax Reference: developer-guide/syntax-reference.md
        - Transform a Stream With KSQL: developer-guide/transform-a-stream-with-ksql.md
        - KSQL Custom Function Reference (UDF and UDAF): developer-guide/udf.md
    - Install and Upgrade:
        - Check the Health of a KSQL Server: installation/check-ksql-server-health.md
        - Configure KSQL CLI: installation/cli-config.md
        - Install KSQL with Docker: installation/install-ksql-with-docker.md
        - Install KSQL: installation/installing.md
        - Upgrade KSQL: installation/upgrading.md
        - Server Configuration:
            - Configure Avro and Confluent Schema Registry for KSQL: installation/server-config/avro-schema.md
            - KSQL Configuration Parameter Reference: installation/server-config/config-reference.md
            - Integrate KSQL with Confluent Control Center: installation/server-config/integrate-ksql-with-confluent-control-center.md
            - Configure Security for KSQL: installation/server-config/security.md
    - Tutorials:
        - Write Streaming Queries Against Apache Kafka® Using KSQL and Confluent Control Center: tutorials/basics-control-center.md 
    - KSQL Capacity Planning: capacity-planning.md
    - KSQL Changelog: changelog.md
    - Frequently Asked Questions: faq.md
    - KSQL Operations: operations.md
    - KSQL Quick Start: quickstart.md
    - Troubleshoot KSQL: troubleshoot-ksql.md


# extra_css:
#     - css/extra.css

# markdown_extensions:
#     - toc:
#         permalink: 
#     - admonition
#     - def_list
#     - mdx_gh_links:
#         user: mkdocs
#         repo: mkdocs

# copyright: Copyright &copy; 2014 <a href="https://twitter.com/_tomchristie">Tom Christie</a>, Maintained by the <a href="/about/release-notes/#maintenance-team">MkDocs Team</a>.
# google_analytics: ['UA-27795084-5', 'mkdocs.org']

# plugins:
#     - search